### ISSUE TITLE
support yarn workspace

### ISSUE THREAD

**Issue by undefined-moe** [cenfun/nmls#1]
doesn't work properly in yarn workspaces.

![image](https://user-images.githubusercontent.com/29992205/117548417-753d3e00-b067-11eb-9543-4ae9ae753f4d.png)

seems that deps couldn't be found

**Comment by cenfun** [comment]
能提供package.json么？得重现查一下才知道，猜可能是link的模块，就不继续往下找了
yarn的workspace统计一直想做还没做好，接下来可能会实现统计workspace的功能

**Comment by undefined-moe** [comment]
/package.json:

```json
{
    "name": "hydro-workspace",
    "private": true,
    "workspaces": ["packages/*"],
    "main": "package.json",
    "version": "1.0.0",
    "license": "AGPL-3.0-only",
    "devDependencies": {
        "@shelf/jest-mongodb": "^1.2.3",
        "@types/cross-spawn": "^6.0.2",
        "@types/jest": "^26.0.23",
        ...
    }
}
```

/packages/hydrooj/package.json:

```json
{
    "name": "hydrooj",
    "version": "2.25.9",
    "bin": "bin/hydrooj.js",
    "main": "dist/loader.js",
    "typings": "dist/loader.d.ts",
    "repository": "https://github.com/hydro-dev/Hydro.git",
    "author": "undefined <i@undefined.moe>",
    "license": "AGPL-3.0-only",
    "engines": {
        "node": ">=14"
    },
    "dependencies": {
        "@hydrooj/utils": "^1.0.14",
        "adm-zip": "^0.5.5",
        "ansi_up": "^5.0.1"
        ...
    },
    "devDependencies": {
        "@types/adm-zip": "^0.4.34",
        "@types/fs-extra": "^9.0.10",
        "@types/inquirer": "^7.3.1",
        "@types/js-yaml": "^4.0.0"
        ...
    }
}
```

**Comment by undefined-moe** [comment]
workspace会尽可能把dep都装在 /node_modules 而不是 /packages/xxx/node_modules

**Comment by cenfun** [comment]
更新了一个3.0的新版，支持统计workspace：
nmls -w

也可以通过参数过滤其中一个或多个包的信息
nmls -w hydrooj
nmls -w hydrooj,hydro-workspace

**Comment by cenfun** [comment]
close

**Comment by undefined-moe** [comment]
今天把 `nmls@3.0.1` 从 workspace 的 devDep 挪到了 `yarn global dir` （全局安装），发现它又炸 workspace 了（

![image](https://user-images.githubusercontent.com/29992205/158030119-35686f77-2485-46a8-845d-f3205578caf5.png)

这个 resolve 估计换成基于 `process.cwd()` 更加合适

**Comment by cenfun** [comment]
![Snipaste_2022-03-13_08-11-46](https://user-images.githubusercontent.com/334577/158039422-059fb987-1de0-4f18-88be-4b1c104fb6e3.jpg)
加了resolve，也加了存在判断，应该至少不会报错了，3.0.2版试试
